// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_get_phi
Rcpp::List cpp_get_phi(const std::vector<double> Y, const std::vector<int> ITEM_INDS, const std::vector<int> WORKER_INDS, const std::vector<double> ALPHA_START, const std::vector<double> BETA_START, const std::vector<double> TAU_START, const double PHI_START, const int J, const int W, const int K, const std::string METHOD, const std::string DATA_TYPE, const bool ITEMS_NUISANCE, const bool WORKER_NUISANCE, const bool VERBOSE, const double SEARCH_RANGE, const int MAX_ITER, const int PROF_SEARCH_RANGE, const int PROF_MAX_ITER, const int ALT_MAX_ITER, const double ALT_TOL);
RcppExport SEXP _AgreementPhi_cpp_get_phi(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP WORKER_INDSSEXP, SEXP ALPHA_STARTSEXP, SEXP BETA_STARTSEXP, SEXP TAU_STARTSEXP, SEXP PHI_STARTSEXP, SEXP JSEXP, SEXP WSEXP, SEXP KSEXP, SEXP METHODSEXP, SEXP DATA_TYPESEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKER_NUISANCESEXP, SEXP VERBOSESEXP, SEXP SEARCH_RANGESEXP, SEXP MAX_ITERSEXP, SEXP PROF_SEARCH_RANGESEXP, SEXP PROF_MAX_ITERSEXP, SEXP ALT_MAX_ITERSEXP, SEXP ALT_TOLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type WORKER_INDS(WORKER_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA_START(ALPHA_STARTSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type BETA_START(BETA_STARTSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type TAU_START(TAU_STARTSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI_START(PHI_STARTSEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const std::string >::type METHOD(METHODSEXP);
    Rcpp::traits::input_parameter< const std::string >::type DATA_TYPE(DATA_TYPESEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKER_NUISANCE(WORKER_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type VERBOSE(VERBOSESEXP);
    Rcpp::traits::input_parameter< const double >::type SEARCH_RANGE(SEARCH_RANGESEXP);
    Rcpp::traits::input_parameter< const int >::type MAX_ITER(MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_SEARCH_RANGE(PROF_SEARCH_RANGESEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_MAX_ITER(PROF_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const int >::type ALT_MAX_ITER(ALT_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const double >::type ALT_TOL(ALT_TOLSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_phi(Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI_START, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, VERBOSE, SEARCH_RANGE, MAX_ITER, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL));
    return rcpp_result_gen;
END_RCPP
}
// cpp_profile_likelihood
double cpp_profile_likelihood(const std::vector<double> Y, const std::vector<int> ITEM_INDS, const std::vector<int> WORKER_INDS, const std::vector<double> ALPHA_START, const std::vector<double> BETA_START, const std::vector<double> TAU_START, const double PHI, const int J, const int W, const int K, const std::string DATA_TYPE, const bool ITEMS_NUISANCE, const bool WORKER_NUISANCE, const double PROF_SEARCH_RANGE, const int PROF_UNI_MAX_ITER, const int ALT_MAX_ITER, const double ALT_TOL);
RcppExport SEXP _AgreementPhi_cpp_profile_likelihood(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP WORKER_INDSSEXP, SEXP ALPHA_STARTSEXP, SEXP BETA_STARTSEXP, SEXP TAU_STARTSEXP, SEXP PHISEXP, SEXP JSEXP, SEXP WSEXP, SEXP KSEXP, SEXP DATA_TYPESEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKER_NUISANCESEXP, SEXP PROF_SEARCH_RANGESEXP, SEXP PROF_UNI_MAX_ITERSEXP, SEXP ALT_MAX_ITERSEXP, SEXP ALT_TOLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type WORKER_INDS(WORKER_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA_START(ALPHA_STARTSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type BETA_START(BETA_STARTSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type TAU_START(TAU_STARTSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const std::string >::type DATA_TYPE(DATA_TYPESEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKER_NUISANCE(WORKER_NUISANCESEXP);
    Rcpp::traits::input_parameter< const double >::type PROF_SEARCH_RANGE(PROF_SEARCH_RANGESEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_UNI_MAX_ITER(PROF_UNI_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const int >::type ALT_MAX_ITER(ALT_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const double >::type ALT_TOL(ALT_TOLSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_profile_likelihood(Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL));
    return rcpp_result_gen;
END_RCPP
}
// cpp_modified_profile_likelihood
double cpp_modified_profile_likelihood(const std::vector<double> Y, const std::vector<int> ITEM_INDS, const std::vector<int> WORKER_INDS, const std::vector<double> ALPHA_MLE, const std::vector<double> BETA_MLE, const std::vector<double> TAU, const double PHI, const double PHI_MLE, const int J, const int W, const int K, const std::string DATA_TYPE, const bool ITEMS_NUISANCE, const bool WORKER_NUISANCE, const double PROF_SEARCH_RANGE, const int PROF_UNI_MAX_ITER, const int ALT_MAX_ITER, const double ALT_TOL);
RcppExport SEXP _AgreementPhi_cpp_modified_profile_likelihood(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP WORKER_INDSSEXP, SEXP ALPHA_MLESEXP, SEXP BETA_MLESEXP, SEXP TAUSEXP, SEXP PHISEXP, SEXP PHI_MLESEXP, SEXP JSEXP, SEXP WSEXP, SEXP KSEXP, SEXP DATA_TYPESEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKER_NUISANCESEXP, SEXP PROF_SEARCH_RANGESEXP, SEXP PROF_UNI_MAX_ITERSEXP, SEXP ALT_MAX_ITERSEXP, SEXP ALT_TOLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type WORKER_INDS(WORKER_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA_MLE(ALPHA_MLESEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type BETA_MLE(BETA_MLESEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type TAU(TAUSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< const double >::type PHI_MLE(PHI_MLESEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const std::string >::type DATA_TYPE(DATA_TYPESEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKER_NUISANCE(WORKER_NUISANCESEXP);
    Rcpp::traits::input_parameter< const double >::type PROF_SEARCH_RANGE(PROF_SEARCH_RANGESEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_UNI_MAX_ITER(PROF_UNI_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const int >::type ALT_MAX_ITER(ALT_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const double >::type ALT_TOL(ALT_TOLSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_modified_profile_likelihood(Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU, PHI, PHI_MLE, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL));
    return rcpp_result_gen;
END_RCPP
}
// cpp_get_se
double cpp_get_se(const std::vector<double> Y, const std::vector<int> ITEM_INDS, const std::vector<int> WORKER_INDS, const std::vector<double> ALPHA_MLE, const std::vector<double> BETA_MLE, const std::vector<double> TAU_MLE, const double PHI_EVAL, const double PHI_MLE, const int J, const int W, const int K, const std::string METHOD, const std::string DATA_TYPE, const bool ITEMS_NUISANCE, const bool WORKER_NUISANCE, const int PROF_SEARCH_RANGE, const int PROF_MAX_ITER, const int ALT_MAX_ITER, const double ALT_TOL);
RcppExport SEXP _AgreementPhi_cpp_get_se(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP WORKER_INDSSEXP, SEXP ALPHA_MLESEXP, SEXP BETA_MLESEXP, SEXP TAU_MLESEXP, SEXP PHI_EVALSEXP, SEXP PHI_MLESEXP, SEXP JSEXP, SEXP WSEXP, SEXP KSEXP, SEXP METHODSEXP, SEXP DATA_TYPESEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKER_NUISANCESEXP, SEXP PROF_SEARCH_RANGESEXP, SEXP PROF_MAX_ITERSEXP, SEXP ALT_MAX_ITERSEXP, SEXP ALT_TOLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type WORKER_INDS(WORKER_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA_MLE(ALPHA_MLESEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type BETA_MLE(BETA_MLESEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type TAU_MLE(TAU_MLESEXP);
    Rcpp::traits::input_parameter< const double >::type PHI_EVAL(PHI_EVALSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI_MLE(PHI_MLESEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const int >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const std::string >::type METHOD(METHODSEXP);
    Rcpp::traits::input_parameter< const std::string >::type DATA_TYPE(DATA_TYPESEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKER_NUISANCE(WORKER_NUISANCESEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_SEARCH_RANGE(PROF_SEARCH_RANGESEXP);
    Rcpp::traits::input_parameter< const int >::type PROF_MAX_ITER(PROF_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const int >::type ALT_MAX_ITER(ALT_MAX_ITERSEXP);
    Rcpp::traits::input_parameter< const double >::type ALT_TOL(ALT_TOLSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_se(Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU_MLE, PHI_EVAL, PHI_MLE, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL));
    return rcpp_result_gen;
END_RCPP
}
// cpp_beta_funs
Rcpp::List cpp_beta_funs(const double A, const double B);
RcppExport SEXP _AgreementPhi_cpp_beta_funs(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_beta_funs(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ibeta_funs
Rcpp::List cpp_ibeta_funs(const double X, const double A, const double B);
RcppExport SEXP _AgreementPhi_cpp_ibeta_funs(SEXP XSEXP, SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ibeta_funs(X, A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cdfbeta_funs
Rcpp::List cpp_cdfbeta_funs(const double X, const double A, const double B);
RcppExport SEXP _AgreementPhi_cpp_cdfbeta_funs(SEXP XSEXP, SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cdfbeta_funs(X, A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cdfbeta_muphi_funs
Rcpp::List cpp_cdfbeta_muphi_funs(const double X, const double MU, const double PHI);
RcppExport SEXP _AgreementPhi_cpp_cdfbeta_muphi_funs(SEXP XSEXP, SEXP MUSEXP, SEXP PHISEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cdfbeta_muphi_funs(X, MU, PHI));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ordinal_loglik
Rcpp::List cpp_ordinal_loglik(const double Y, const double MU, const double PHI, const int K);
RcppExport SEXP _AgreementPhi_cpp_ordinal_loglik(SEXP YSEXP, SEXP MUSEXP, SEXP PHISEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ordinal_loglik(Y, MU, PHI, K));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ordinal_item_loglik
Rcpp::List cpp_ordinal_item_loglik(const std::vector<double> Y, const std::vector<double> ITEM_INDS, const double ALPHA, const double PHI, const int K, const int J, const int ITEM);
RcppExport SEXP _AgreementPhi_cpp_ordinal_item_loglik(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP ALPHASEXP, SEXP PHISEXP, SEXP KSEXP, SEXP JSEXP, SEXP ITEMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const double >::type ALPHA(ALPHASEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const int >::type ITEM(ITEMSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ordinal_item_loglik(Y, ITEM_INDS, ALPHA, PHI, K, J, ITEM));
    return rcpp_result_gen;
END_RCPP
}
// cpp_log_det_obs_info
double cpp_log_det_obs_info(const std::vector<double> Y, const std::vector<double> ITEM_INDS, const std::vector<double> ALPHA, const double PHI, const int K, const int J, const bool ITEMS_NUISANCE, const bool WORKERS_NUISANCE);
RcppExport SEXP _AgreementPhi_cpp_log_det_obs_info(SEXP YSEXP, SEXP ITEM_INDSSEXP, SEXP ALPHASEXP, SEXP PHISEXP, SEXP KSEXP, SEXP JSEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKERS_NUISANCESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA(ALPHASEXP);
    Rcpp::traits::input_parameter< const double >::type PHI(PHISEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKERS_NUISANCE(WORKERS_NUISANCESEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_det_obs_info(Y, ITEM_INDS, ALPHA, PHI, K, J, ITEMS_NUISANCE, WORKERS_NUISANCE));
    return rcpp_result_gen;
END_RCPP
}
// cpp_log_det_E0d0d1
double cpp_log_det_E0d0d1(const std::vector<double> ITEM_INDS, const std::vector<double> ALPHA0, const std::vector<double> ALPHA1, const double PHI0, const double PHI1, const int K, const int J, const bool ITEMS_NUISANCE, const bool WORKERS_NUISANCE);
RcppExport SEXP _AgreementPhi_cpp_log_det_E0d0d1(SEXP ITEM_INDSSEXP, SEXP ALPHA0SEXP, SEXP ALPHA1SEXP, SEXP PHI0SEXP, SEXP PHI1SEXP, SEXP KSEXP, SEXP JSEXP, SEXP ITEMS_NUISANCESEXP, SEXP WORKERS_NUISANCESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double> >::type ITEM_INDS(ITEM_INDSSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA0(ALPHA0SEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type ALPHA1(ALPHA1SEXP);
    Rcpp::traits::input_parameter< const double >::type PHI0(PHI0SEXP);
    Rcpp::traits::input_parameter< const double >::type PHI1(PHI1SEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type J(JSEXP);
    Rcpp::traits::input_parameter< const bool >::type ITEMS_NUISANCE(ITEMS_NUISANCESEXP);
    Rcpp::traits::input_parameter< const bool >::type WORKERS_NUISANCE(WORKERS_NUISANCESEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_det_E0d0d1(ITEM_INDS, ALPHA0, ALPHA1, PHI0, PHI1, K, J, ITEMS_NUISANCE, WORKERS_NUISANCE));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AgreementPhi_cpp_get_phi", (DL_FUNC) &_AgreementPhi_cpp_get_phi, 21},
    {"_AgreementPhi_cpp_profile_likelihood", (DL_FUNC) &_AgreementPhi_cpp_profile_likelihood, 17},
    {"_AgreementPhi_cpp_modified_profile_likelihood", (DL_FUNC) &_AgreementPhi_cpp_modified_profile_likelihood, 18},
    {"_AgreementPhi_cpp_get_se", (DL_FUNC) &_AgreementPhi_cpp_get_se, 19},
    {"_AgreementPhi_cpp_beta_funs", (DL_FUNC) &_AgreementPhi_cpp_beta_funs, 2},
    {"_AgreementPhi_cpp_ibeta_funs", (DL_FUNC) &_AgreementPhi_cpp_ibeta_funs, 3},
    {"_AgreementPhi_cpp_cdfbeta_funs", (DL_FUNC) &_AgreementPhi_cpp_cdfbeta_funs, 3},
    {"_AgreementPhi_cpp_cdfbeta_muphi_funs", (DL_FUNC) &_AgreementPhi_cpp_cdfbeta_muphi_funs, 3},
    {"_AgreementPhi_cpp_ordinal_loglik", (DL_FUNC) &_AgreementPhi_cpp_ordinal_loglik, 4},
    {"_AgreementPhi_cpp_ordinal_item_loglik", (DL_FUNC) &_AgreementPhi_cpp_ordinal_item_loglik, 7},
    {"_AgreementPhi_cpp_log_det_obs_info", (DL_FUNC) &_AgreementPhi_cpp_log_det_obs_info, 8},
    {"_AgreementPhi_cpp_log_det_E0d0d1", (DL_FUNC) &_AgreementPhi_cpp_log_det_E0d0d1, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_AgreementPhi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
