# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_get_phi <- function(Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI_START, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, VERBOSE, SEARCH_RANGE, MAX_ITER, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL) {
    .Call(`_AgreementPhi_cpp_get_phi`, Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI_START, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, VERBOSE, SEARCH_RANGE, MAX_ITER, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL)
}

cpp_profile_likelihood <- function(Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL) {
    .Call(`_AgreementPhi_cpp_profile_likelihood`, Y, ITEM_INDS, WORKER_INDS, ALPHA_START, BETA_START, TAU_START, PHI, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL)
}

cpp_modified_profile_likelihood <- function(Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU, PHI, PHI_MLE, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL) {
    .Call(`_AgreementPhi_cpp_modified_profile_likelihood`, Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU, PHI, PHI_MLE, J, W, K, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_UNI_MAX_ITER, ALT_MAX_ITER, ALT_TOL)
}

cpp_get_se <- function(Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU_MLE, PHI_EVAL, PHI_MLE, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL) {
    .Call(`_AgreementPhi_cpp_get_se`, Y, ITEM_INDS, WORKER_INDS, ALPHA_MLE, BETA_MLE, TAU_MLE, PHI_EVAL, PHI_MLE, J, W, K, METHOD, DATA_TYPE, ITEMS_NUISANCE, WORKER_NUISANCE, PROF_SEARCH_RANGE, PROF_MAX_ITER, ALT_MAX_ITER, ALT_TOL)
}

cpp_beta_funs <- function(A, B) {
    .Call(`_AgreementPhi_cpp_beta_funs`, A, B)
}

cpp_ibeta_funs <- function(X, A, B) {
    .Call(`_AgreementPhi_cpp_ibeta_funs`, X, A, B)
}

cpp_cdfbeta_funs <- function(X, A, B) {
    .Call(`_AgreementPhi_cpp_cdfbeta_funs`, X, A, B)
}

cpp_cdfbeta_muphi_funs <- function(X, MU, PHI) {
    .Call(`_AgreementPhi_cpp_cdfbeta_muphi_funs`, X, MU, PHI)
}

cpp_ordinal_loglik <- function(Y, MU, PHI, K) {
    .Call(`_AgreementPhi_cpp_ordinal_loglik`, Y, MU, PHI, K)
}

cpp_ordinal_item_loglik <- function(Y, ITEM_INDS, ALPHA, PHI, K, J, ITEM) {
    .Call(`_AgreementPhi_cpp_ordinal_item_loglik`, Y, ITEM_INDS, ALPHA, PHI, K, J, ITEM)
}

cpp_log_det_obs_info <- function(Y, ITEM_INDS, ALPHA, PHI, K, J, ITEMS_NUISANCE = FALSE, WORKERS_NUISANCE = FALSE) {
    .Call(`_AgreementPhi_cpp_log_det_obs_info`, Y, ITEM_INDS, ALPHA, PHI, K, J, ITEMS_NUISANCE, WORKERS_NUISANCE)
}

cpp_log_det_E0d0d1 <- function(ITEM_INDS, ALPHA0, ALPHA1, PHI0, PHI1, K, J, ITEMS_NUISANCE = FALSE, WORKERS_NUISANCE = FALSE) {
    .Call(`_AgreementPhi_cpp_log_det_E0d0d1`, ITEM_INDS, ALPHA0, ALPHA1, PHI0, PHI1, K, J, ITEMS_NUISANCE, WORKERS_NUISANCE)
}

